name: "Hello Actions"
description: "Greet Githubaction"
author: "jaherran@github.com"

inputs:
  MY_NAME:
    description: "who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"